# Generated by Django 2.1.4 on 2019-04-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
