# Generated by Django 2.1.4 on 2019-04-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0010_auto_20190414_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerNoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='summernoteImage/')),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catImage/'),
        ),
    ]
