# Generated by Django 2.1.4 on 2019-04-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0011_auto_20190415_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='summernoteimage',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
