# Generated by Django 2.1.4 on 2019-04-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0013_auto_20190415_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('notice', 'Notice'), ('reply', 'Reply')], max_length=30, null=True),
        ),
    ]
