# Generated by Django 2.1.4 on 2019-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0015_notification_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recognized',
            field=models.BooleanField(default=False),
        ),
    ]
