# Generated by Django 2.1.4 on 2019-04-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0016_user_is_recognized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('reply', 'Reply'), ('notice', 'Notice')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_recognized',
            field=models.CharField(default='in_progress', max_length=40),
        ),
    ]
