# Generated by Django 2.1.4 on 2019-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0017_auto_20190415_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_recognized',
            field=models.CharField(default='in_progress', max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('notice', 'Notice'), ('reply', 'Reply')], max_length=30, null=True),
        ),
    ]
