# Generated by Django 2.1.4 on 2019-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0018_auto_20190415_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('silver', 'Silver'), ('bronze', 'Bronze'), ('gold', 'Gold')], max_length=30, null=True),
        ),
    ]
