# Generated by Django 2.1.4 on 2019-04-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0020_auto_20190423_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('bronze', 'Bronze')], max_length=30, null=True),
        ),
    ]
